### ISSUE TITLE
[미션A] 홈링크 (텍스트) 테스트 

### ISSUE THREAD

**Issue by chacha912** [chacha912/coupang-signin#5]
![image](https://user-images.githubusercontent.com/81357083/130346859-5fdedaf1-9b69-49ff-92d2-dc86b9598790.png)

- [x] 홈링크 (텍스트) 스토리 파일 작성
- [x] props항목별 description, default, control 이 표시되도록 설정

## 📚 devlog
- 홈링크 기능- `a` 태그와 `href` 속성 추가
- 테스트 여러개일 경우 `Template` 만들어 사용

**Comment by yeongjong310** [comment]
description: 
- 컴포넌트의 proptype의 각 프로퍼티 상단에 /** 주석 */ 형태로 기입한다.

default: 
- 컴포넌트의 defaultProps에 설정한 값이 스토리 북의 default 값으로  반영된다. 
- 스토리의 args 프로퍼티에 설정한 값이 control의 기본 값으로 반영된다. 

control:
- 초기에  ```const Template = (args) => <HomeLink {...args} />;``` 방식으로 template를 만들어 놓고 ```Template.bind({}, {children: <Logo />} );``` 방식으로 children을 넘겨주었다. 이때 ```{children: <Logo />}```에 의해 props  내의 프로퍼티가 모두 삭제되는 것으로 보이며 control을 meta에 명시해 주어야만 설정되는 오류가 발생했다. 따라서 children을 꼭 아래와 같은 방식으로 적용하자.
```js
HomeLink.args = {
  children: <Logo />,
};
